import { defineConfig } from 'orval';

export default defineConfig({
  'serezin-gaming-api-file': {
    input: 'src/libs/api/specifications/swagger-spec.yaml',
    output: {
      mode: 'tags-split',
      target: 'src/libs/api/endpoints/',
      schemas: 'src/libs/api/models',
      client: 'react-query',
      mock: false,
      prettier: true,
      override: {
        // mock: {
        //   baseUrl: 'https://mock.serezin-gaming.fr'
        // },
        header: () => [`Generated by orval 🍺`, `Do not edit manually.`],
        mutator: {
          path: 'src/libs/api/custom/customAxiosInstance.ts',
          name: 'customAxiosInstance'
        }
      }
    }
  }
});
