/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticateUserDto } from './authenticateUserDto';
import type { AuthenticationExchangeCodeResponseDtoMeta } from './authenticationExchangeCodeResponseDtoMeta';

export interface AuthenticationExchangeCodeResponseDto {
  data: AuthenticateUserDto;
  message: string;
  meta: AuthenticationExchangeCodeResponseDtoMeta;
  statusCode: number;
}
