/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticateUserDtoDiscord } from './authenticateUserDtoDiscord';
import type { AuthenticateUserDtoRiot } from './authenticateUserDtoRiot';

export interface AuthenticateUserDto {
  discord: AuthenticateUserDtoDiscord;
  /** @nullable */
  riot: AuthenticateUserDtoRiot;
}
