/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticationExchangeCodeBadRequestResponseDtoErrorMessage } from './authenticationExchangeCodeBadRequestResponseDtoErrorMessage';

export type AuthenticationExchangeCodeBadRequestResponseDtoError = {
  message?: AuthenticationExchangeCodeBadRequestResponseDtoErrorMessage;
};
