/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticationExchangeCodeBadRequestResponseDtoError } from './authenticationExchangeCodeBadRequestResponseDtoError';

export interface AuthenticationExchangeCodeBadRequestResponseDto {
  error: AuthenticationExchangeCodeBadRequestResponseDtoError;
  statusCode: number;
}
