/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type AuthenticateUserDtoDiscord = {
  avatar?: string;
  /** @nullable */
  global_name?: string | null;
  id?: string;
  username?: string;
};
