/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticateUserDto } from './authenticateUserDto';
import type { AuthenticateUserOkDtoMeta } from './authenticateUserOkDtoMeta';

export interface AuthenticateUserOkDto {
  data: AuthenticateUserDto;
  message: string;
  meta: AuthenticateUserOkDtoMeta;
  statusCode: number;
}
