/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

/**
 * @nullable
 */
export type AuthenticateUserDtoRiot = {
  friend_sync?: boolean;
  id?: string;
  metadata_visibility?: number;
  name?: string;
  show_activity?: boolean;
  two_way_link?: boolean;
  type?: string;
  verified?: boolean;
  visibility?: number;
} | null;
