/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type AuthenticateUserDtoUser = {
  /** @nullable */
  accent_color?: number | null;
  avatar?: string;
  /** @nullable */
  banner?: string | null;
  /** @nullable */
  banner_color?: number | null;
  /** @nullable */
  clan?: string | null;
  discriminator?: string;
  flags?: number;
  /** @nullable */
  global_name?: string | null;
  id?: string;
  /** @nullable */
  primary_guild?: string | null;
  public_flags?: number;
  username?: string;
};
