/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticateUserDtoRiot } from './authenticateUserDtoRiot';
import type { AuthenticateUserDtoToken } from './authenticateUserDtoToken';
import type { AuthenticateUserDtoUser } from './authenticateUserDtoUser';

export interface AuthenticateUserDto {
  /** @nullable */
  riot: AuthenticateUserDtoRiot;
  token: AuthenticateUserDtoToken;
  user: AuthenticateUserDtoUser;
}
