/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { AuthenticationTokenDto } from './authenticationTokenDto';
import type { AuthenticationExchangeCodeResponseDtoMeta } from './authenticationExchangeCodeResponseDtoMeta';

export interface AuthenticationExchangeCodeResponseDto {
  data: AuthenticationTokenDto;
  message: string;
  meta: AuthenticationExchangeCodeResponseDtoMeta;
  statusCode: number;
}
