/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface AuthenticationTokenDto {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  scope: string;
  token_type: string;
}
