/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { ForbiddenResponseDtoErrorMessage } from './forbiddenResponseDtoErrorMessage';

export type ForbiddenResponseDtoError = {
  message?: ForbiddenResponseDtoErrorMessage;
};
