/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { ForbiddenResponseDtoError } from './forbiddenResponseDtoError';

export interface ForbiddenResponseDto {
  error: ForbiddenResponseDtoError;
  statusCode: number;
}
