/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { InternalServerErrorResponseDtoErrorMessage } from './internalServerErrorResponseDtoErrorMessage';

export type InternalServerErrorResponseDtoError = {
  message?: InternalServerErrorResponseDtoErrorMessage;
};
