/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { InternalServerErrorResponseDtoError } from './internalServerErrorResponseDtoError';

export interface InternalServerErrorResponseDto {
  error: InternalServerErrorResponseDtoError;
  statusCode: number;
}
