/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface ResponsePaginationMetaDto {
  currentPage: number;
  haveNextPage: boolean;
  havePreviousPage: boolean;
  itemsPerPage: number;
  totalItems: number;
  totalPages: number;
}
