/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentBadRequestResponseDtoError } from './tournamentBadRequestResponseDtoError';

export interface TournamentBadRequestResponseDto {
  error: TournamentBadRequestResponseDtoError;
  statusCode: number;
}
