/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentNotFoundResponseDtoError } from './tournamentNotFoundResponseDtoError';

export interface TournamentNotFoundResponseDto {
  error: TournamentNotFoundResponseDtoError;
  statusCode: number;
}
