/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentDto } from './tournamentDto';
import type { TournamentCreatedResponseDtoMeta } from './tournamentCreatedResponseDtoMeta';

export interface TournamentCreatedResponseDto {
  data: TournamentDto;
  message: string;
  meta: TournamentCreatedResponseDtoMeta;
  statusCode: number;
}
