/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentNotFoundResponseDtoErrorMessage } from './tournamentNotFoundResponseDtoErrorMessage';

export type TournamentNotFoundResponseDtoError = {
  message?: TournamentNotFoundResponseDtoErrorMessage;
};
