/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentBadRequestResponseDtoErrorMessage } from './tournamentBadRequestResponseDtoErrorMessage';

export type TournamentBadRequestResponseDtoError = {
  message?: TournamentBadRequestResponseDtoErrorMessage;
};
