/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentDto } from './tournamentDto';
import type { ResponsePaginationMetaDto } from './responsePaginationMetaDto';

export interface TournamentArrayResponseDto {
  data: TournamentDto[];
  message: string;
  meta: ResponsePaginationMetaDto;
  statusCode: number;
}
