/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { TournamentDto } from './tournamentDto';
import type { TournamentResponseDtoMeta } from './tournamentResponseDtoMeta';

export interface TournamentResponseDto {
  data: TournamentDto;
  message: string;
  meta: TournamentResponseDtoMeta;
  statusCode: number;
}
